package main

import (
	"flag"
	"fmt"
	"io"
	"os"
	"strings"
	"time"
)

// commandDoc describes a top-level subcommand for shell completion and the
// generated man page. The list is hand-maintained alongside the runRoot
// dispatch switch; completion_test.go asserts the two stay in sync so a new
// command cannot be added without also surfacing it to completions and docs.
type commandDoc struct {
	Name    string
	Summary string
}

// topLevelCommands is the user-facing command surface. Order is the order shown
// in completions and the man page.
var topLevelCommands = []commandDoc{
	{"check", "Evaluate a JSONL batch of tool calls against a policy"},
	{"explain", "Show the decision trace for a single tool call"},
	{"validate", "Validate a policy file"},
	{"policy", "Policy subcommands: validate, test"},
	{"proxy", "Run the stdio MCP policy proxy"},
	{"proxy-http", "Run the streamable-HTTP MCP policy proxy"},
	{"audit", "Audit-log subcommands: verify, summarize, export, keygen, anchor"},
	{"init", "Scaffold a starter policy (optionally from a pack)"},
	{"demo", "Run the built-in demonstration"},
	{"completion", "Generate a shell completion script (bash, zsh, fish)"},
	{"man", "Generate the agentfence(1) man page in roff format"},
	{"version", "Print version, OS, and architecture"},
}

// subcommandGroups maps a command that has its own subcommands to that set, so
// completions can offer the second word too.
var subcommandGroups = map[string][]string{
	"policy":     {"validate", "test"},
	"audit":      {"verify", "summarize", "export", "keygen", "anchor"},
	"completion": {"bash", "zsh", "fish"},
}

// supportedShells lists the shells `completion` can emit, in a stable order.
var supportedShells = []string{"bash", "zsh", "fish"}

func commandNames() []string {
	names := make([]string, len(topLevelCommands))
	for i, c := range topLevelCommands {
		names[i] = c.Name
	}
	return names
}

// runCompletion implements `agentfence completion <shell>`, printing a shell
// completion script to stdout. It takes exactly one positional argument naming
// the shell.
func runCompletion(args []string) error {
	fs := flag.NewFlagSet("completion", flag.ContinueOnError)
	fs.Usage = func() {
		out := fs.Output()
		fmt.Fprintln(out, "Usage: agentfence completion <bash|zsh|fish>")
		fmt.Fprintln(out, "")
		fmt.Fprintln(out, "Print a shell completion script to stdout. Install it where your shell")
		fmt.Fprintln(out, "loads completions, for example:")
		fmt.Fprintln(out, "  agentfence completion bash > /etc/bash_completion.d/agentfence")
		fmt.Fprintln(out, "  agentfence completion zsh  > \"${fpath[1]}/_agentfence\"")
		fmt.Fprintln(out, "  agentfence completion fish > ~/.config/fish/completions/agentfence.fish")
	}
	if err := fs.Parse(args); err != nil {
		return handleFlagParseErr(err)
	}
	if fs.NArg() != 1 {
		return fmt.Errorf("completion requires exactly one shell argument (%s); got %d", strings.Join(supportedShells, ", "), fs.NArg())
	}
	return writeCompletion(os.Stdout, fs.Arg(0))
}

// writeCompletion writes the completion script for shell to w.
func writeCompletion(w io.Writer, shell string) error {
	switch shell {
	case "bash":
		return writeBashCompletion(w)
	case "zsh":
		return writeZshCompletion(w)
	case "fish":
		return writeFishCompletion(w)
	default:
		return fmt.Errorf("unsupported shell %q (supported: %s)", shell, strings.Join(supportedShells, ", "))
	}
}

func writeBashCompletion(w io.Writer) error {
	var b strings.Builder
	b.WriteString("# bash completion for agentfence — generated by `agentfence completion bash`.\n")
	b.WriteString("_agentfence() {\n")
	b.WriteString("    local cur=\"${COMP_WORDS[COMP_CWORD]}\"\n")
	fmt.Fprintf(&b, "    local commands=%q\n", strings.Join(commandNames(), " "))
	b.WriteString("    if [[ ${COMP_CWORD} -eq 1 ]]; then\n")
	b.WriteString("        COMPREPLY=( $(compgen -W \"${commands}\" -- \"${cur}\") )\n")
	b.WriteString("        return 0\n")
	b.WriteString("    fi\n")
	b.WriteString("    if [[ ${COMP_CWORD} -eq 2 ]]; then\n")
	b.WriteString("        case \"${COMP_WORDS[1]}\" in\n")
	for _, name := range sortedGroupKeys() {
		fmt.Fprintf(&b, "            %s) COMPREPLY=( $(compgen -W %q -- \"${cur}\") ) ;;\n", name, strings.Join(subcommandGroups[name], " "))
	}
	b.WriteString("        esac\n")
	b.WriteString("    fi\n")
	b.WriteString("}\n")
	b.WriteString("complete -F _agentfence agentfence\n")
	_, err := io.WriteString(w, b.String())
	return err
}

func writeZshCompletion(w io.Writer) error {
	var b strings.Builder
	b.WriteString("#compdef agentfence\n")
	b.WriteString("# zsh completion for agentfence — generated by `agentfence completion zsh`.\n")
	b.WriteString("_agentfence() {\n")
	b.WriteString("    local -a commands\n")
	b.WriteString("    commands=(\n")
	for _, c := range topLevelCommands {
		fmt.Fprintf(&b, "        '%s:%s'\n", c.Name, zshEscape(c.Summary))
	}
	b.WriteString("    )\n")
	b.WriteString("    _arguments -C '1: :->command' '*:: :->args'\n")
	b.WriteString("    case $state in\n")
	b.WriteString("        command) _describe -t commands 'agentfence command' commands ;;\n")
	b.WriteString("        args)\n")
	// In the '*::' (double-colon) rest-args state, zsh rescopes $words so that
	// $words[1] is the subcommand (verified: `audit <TAB>` => $words[1]=audit,
	// $words[2] empty). Do not switch this to $words[2].
	b.WriteString("            # '*::' rescopes $words; $words[1] is the subcommand here.\n")
	b.WriteString("            case $words[1] in\n")
	for _, name := range sortedGroupKeys() {
		fmt.Fprintf(&b, "                %s) _values '%s subcommand' %s ;;\n", name, name, strings.Join(subcommandGroups[name], " "))
	}
	b.WriteString("            esac\n")
	b.WriteString("            ;;\n")
	b.WriteString("    esac\n")
	b.WriteString("}\n")
	b.WriteString("_agentfence \"$@\"\n")
	_, err := io.WriteString(w, b.String())
	return err
}

func writeFishCompletion(w io.Writer) error {
	var b strings.Builder
	b.WriteString("# fish completion for agentfence — generated by `agentfence completion fish`.\n")
	b.WriteString("complete -c agentfence -f\n")
	for _, c := range topLevelCommands {
		fmt.Fprintf(&b, "complete -c agentfence -n __fish_use_subcommand -a %s -d %q\n", c.Name, c.Summary)
	}
	for _, name := range sortedGroupKeys() {
		fmt.Fprintf(&b, "complete -c agentfence -n '__fish_seen_subcommand_from %s' -a %q\n", name, strings.Join(subcommandGroups[name], " "))
	}
	_, err := io.WriteString(w, b.String())
	return err
}

// sortedGroupKeys returns subcommandGroups keys in the topLevelCommands order so
// generated scripts are deterministic.
func sortedGroupKeys() []string {
	keys := make([]string, 0, len(subcommandGroups))
	for _, c := range topLevelCommands {
		if _, ok := subcommandGroups[c.Name]; ok {
			keys = append(keys, c.Name)
		}
	}
	return keys
}

func zshEscape(s string) string {
	// Single-quoted zsh strings escape an embedded quote as '\''.
	return strings.ReplaceAll(s, "'", `'\''`)
}

// runMan implements `agentfence man`, printing an agentfence(1) man page in
// roff format to stdout. It takes no arguments.
func runMan(args []string) error {
	fs := flag.NewFlagSet("man", flag.ContinueOnError)
	fs.Usage = func() {
		out := fs.Output()
		fmt.Fprintln(out, "Usage: agentfence man")
		fmt.Fprintln(out, "")
		fmt.Fprintln(out, "Print the agentfence(1) man page in roff format to stdout, e.g.:")
		fmt.Fprintln(out, "  agentfence man > /usr/local/share/man/man1/agentfence.1")
	}
	if err := fs.Parse(args); err != nil {
		return handleFlagParseErr(err)
	}
	if fs.NArg() > 0 {
		return fmt.Errorf("man takes no arguments; got %q", fs.Arg(0))
	}
	return writeManPage(os.Stdout)
}

// writeManPage writes the agentfence(1) roff man page to w.
func writeManPage(w io.Writer) error {
	var b strings.Builder
	date := time.Now().UTC().Format("2006-01-02")
	fmt.Fprintf(&b, ".TH AGENTFENCE 1 %q %q \"AgentFence Manual\"\n", date, "agentfence "+Version)
	b.WriteString(".SH NAME\n")
	b.WriteString("agentfence \\- policy firewall for MCP tool calls\n")
	b.WriteString(".SH SYNOPSIS\n")
	b.WriteString(".B agentfence\n")
	b.WriteString(".I command\n")
	b.WriteString("[\\fIarguments\\fR]\n")
	b.WriteString(".SH DESCRIPTION\n")
	b.WriteString("AgentFence is a local-first policy gate for Model Context Protocol (MCP)\n")
	b.WriteString("tool calls. It evaluates calls against a YAML policy and can run as a CLI\n")
	b.WriteString("gate or as a stdio/HTTP proxy in front of an MCP server, with a\n")
	b.WriteString("tamper-evident audit log.\n")
	b.WriteString(".SH COMMANDS\n")
	for _, c := range topLevelCommands {
		fmt.Fprintf(&b, ".TP\n.B %s\n%s\n", c.Name, manEscape(c.Summary))
	}
	b.WriteString(".SH SEE ALSO\n")
	b.WriteString("Project documentation under \\fIdocs/\\fR, including\n")
	b.WriteString("\\fIdocs/policy-language.md\\fR and \\fIdocs/integration-guide.md\\fR.\n")
	_, err := io.WriteString(w, b.String())
	return err
}

func manEscape(s string) string {
	// Escape backslashes so summaries render literally, then neutralize a
	// leading "." or "'" — roff treats those as a control request at the
	// start of a line — by prefixing the zero-width escape "\&".
	s = strings.ReplaceAll(s, `\`, `\\`)
	if strings.HasPrefix(s, ".") || strings.HasPrefix(s, "'") {
		s = `\&` + s
	}
	return s
}
